### ISSUE TITLE
Stacktrace

### ISSUE THREAD

**Issue by MarcelH-Tabeo** [alexkohler/nakedret#31]
I get tis:
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x100eb5b04]

goroutine 14 [running]:
go/types.(*Checker).handleBailout(0x14000155600, 0x140009cdb98)
        /usr/local/go/src/go/types/check.go:367 +0x9c
panic({0x10108b300?, 0x10128bc20?})
        /usr/local/go/src/runtime/panic.go:770 +0x124
go/types.(*StdSizes).Sizeof(0x0, {0x1010e0b68, 0x10128f840})
        /usr/local/go/src/go/types/sizes.go:228 +0x314
go/types.(*Config).sizeof(...)
        /usr/local/go/src/go/types/sizes.go:333
go/types.representableConst.func1({0x1010e0b68?, 0x10128f840?})
        /usr/local/go/src/go/types/const.go:76 +0x9c
go/types.representableConst({0x1010e1e70, 0x101284660}, 0x14000155600, 0x10128f840, 0x140009cb3d8)
        /usr/local/go/src/go/types/const.go:92 +0x138
go/types.(*Checker).representation(0x14000155600, 0x1400046f500, 0x10128f840)
        /usr/local/go/src/go/types/const.go:256 +0x68
go/types.(*Checker).implicitTypeAndValue(0x14000155600, 0x1400046f500, {0x1010e0b68, 0x10128f840})
        /usr/local/go/src/go/types/expr.go:375 +0x304
go/types.(*Checker).convertUntyped(0x14000155600, 0x1400046f500, {0x1010e0b68, 0x10128f840})
        /usr/local/go/src/go/types/const.go:289 +0x30
go/types.(*Checker).matchTypes(0x14000155600, 0x1400046f480, 0x1400046f500)
        /usr/local/go/src/go/types/expr.go:926 +0x7c
go/types.(*Checker).binary(0x14000155600, 0x1400046f480, {0x1010e14f0, 0x14000432510}, {0x1010e1520, 0x14000295900}, {0x1010e1a00, 0x14000447840}, 0x29, 0x12a0b07)
        /usr/local/go/src/go/types/expr.go:800 +0x114
go/types.(*Checker).exprInternal(0x14000155600, 0x0, 0x1400046f480, {0x1010e14f0, 0x14000432510}, {0x0, 0x0})
        /usr/local/go/src/go/types/expr.go:1416 +0x1d4
go/types.(*Checker).rawExpr(0x14000155600, 0x0, 0x1400046f480, {0x1010e14f0?, 0x14000432510?}, {0x0?, 0x0?}, 0x0)
        /usr/local/go/src/go/types/expr.go:979 +0x12c
go/types.(*Checker).expr(0x14000155600, 0x0?, 0x1400046f480, {0x1010e14f0?, 0x14000432510?})
        /usr/local/go/src/go/types/expr.go:1513 +0x38
go/types.(*Checker).binary(0x14000155600, 0x1400046f480, {0x1010e14f0, 0x140004325a0}, {0x1010e14f0, 0x14000432510}, {0x1010e14f0, 0x14000432570}, 0x22, 0x12a0b0b)
        /usr/local/go/src/go/types/expr.go:783 +0x70
go/types.(*Checker).exprInternal(0x14000155600, 0x0, 0x1400046f480, {0x1010e14f0, 0x140004325a0}, {0x0, 0x0})
        /usr/local/go/src/go/types/expr.go:1416 +0x1d4
go/types.(*Checker).rawExpr(0x14000155600, 0x0, 0x1400046f480, {0x1010e14f0?, 0x140004325a0?}, {0x0?, 0x0?}, 0x0)
        /usr/local/go/src/go/types/expr.go:979 +0x12c
go/types.(*Checker).expr(0x14000155600, 0x1010e0858?, 0x1400046f480, {0x1010e14f0?, 0x140004325a0?})
        /usr/local/go/src/go/types/expr.go:1513 +0x38
go/types.(*Checker).stmt(0x14000155600, 0x0, {0x1010e16a0, 0x14000295980})
        /usr/local/go/src/go/types/stmt.go:570 +0xda4
go/types.(*Checker).stmtList(0x14000155600, 0x0, {0x140004faa00?, 0x0?, 0x26?})
        /usr/local/go/src/go/types/stmt.go:121 +0x88
go/types.(*Checker).funcBody(0x14000155600, 0x1010e0bb8?, {0x140005061e0?, 0x140001301c0?}, 0x1400046ec40, 0x140004326f0, {0x0?, 0x0?})
        /usr/local/go/src/go/types/stmt.go:41 +0x21c
go/types.(*Checker).funcDecl.func1()
        /usr/local/go/src/go/types/decl.go:852 +0x44
go/types.(*Checker).processDelayed(0x14000155600, 0x0)
        /usr/local/go/src/go/types/check.go:467 +0x12c
go/types.(*Checker).checkFiles(0x14000155600, {0x14000169608, 0x1, 0x1})
        /usr/local/go/src/go/types/check.go:411 +0x188
go/types.(*Checker).Files(...)
        /usr/local/go/src/go/types/check.go:372
golang.org/x/tools/go/packages.(*loader).loadPackage(0x1400015a000, 0x14000483ce0)
        /Users/Marcello/go/pkg/mod/golang.org/x/tools@v0.8.0/go/packages/packages.go:1052 +0x870
golang.org/x/tools/go/packages.(*loader).loadRecursive.func1()
        /Users/Marcello/go/pkg/mod/golang.org/x/tools@v0.8.0/go/packages/packages.go:851 +0x178
sync.(*Once).doSlow(0x0?, 0x0?)
        /usr/local/go/src/sync/once.go:74 +0x100
sync.(*Once).Do(...)
        /usr/local/go/src/sync/once.go:65
golang.org/x/tools/go/packages.(*loader).loadRecursive(0x0?, 0x0?)
        /Users/Marcello/go/pkg/mod/golang.org/x/tools@v0.8.0/go/packages/packages.go:839 +0x50
golang.org/x/tools/go/packages.(*loader).loadRecursive.func1.1(0x0?)
        /Users/Marcello/go/pkg/mod/golang.org/x/tools@v0.8.0/go/packages/packages.go:846 +0x30
created by golang.org/x/tools/go/packages.(*loader).loadRecursive.func1 in goroutine 26
        /Users/Marcello/go/pkg/mod/golang.org/x/tools@v0.8.0/go/packages/packages.go:845 +0x84

```

**Comment by alexkohler** [comment]
Believe this should be fixed by #32.
